const Timeline = [
  {
    id: 1,
    titulo: "Paradoxia",
    subtitulo: "o começo de tudo",
    ano: "2-1 A.BB.",
    duracao: "",
    cidade: "Agalor",
    detalhes: "",
  },
  {
    id: 2,
    titulo: "Storm King's Thunder",
    subtitulo: "um recomeço",
    ano: "1489-1490 D.R.",
    duracao: "",
    cidade: "Waterdeep",
    detalhes: "",
  },
  {
    id: 3,
    titulo: "A Mina Perdida de Phandelver (Saga Phandalin 1)",
    subtitulo: "pesquisa",
    ano: "1491 D.R",
    duracao: "",
    cidade: "Neverwinter",
    detalhes: "",
  },
  {
    id: 4,
    titulo: "Dragons of Icespire Peak (Saga Phandalin 2)",
    subtitulo: "maquinações",
    ano: "1491-1492 D.R",
    duracao: "",
    cidade: "Phandalin",
    detalhes: "",
  },
  {
    id: 5,
    titulo: "Strixhaven de Paradoxia",
    subtitulo: "um mistério",
    ano: "87 D.BB.",
    duracao: "",
    cidade: "Strixhaven",
    detalhes: "",
  },
  {
    id: 6,
    titulo: "A Busca de Thalivar (Saga Phandalin pós)",
    subtitulo: "encontrando ferramentas",
    ano: "1492 D.R.",
    duracao: "",
    cidade: "Phandalin",
    detalhes: "",
  },
  {
    id: 7,
    titulo: "Tomb of Annihilation",
    subtitulo: "causas",
    ano: "1493 D.R.",
    duracao: "",
    cidade: "Porto Nianzaru",
    detalhes: "",
  },
  {
    id: 8,
    titulo: "Dualidade (Online)",
    subtitulo: "consequências",
    ano: "1495- D.R.",
    duracao: "",
    cidade: "Waterdeep",
    detalhes: "",
  },
  {
    id: 9,
    titulo: "Dualidade (Presencial)",
    subtitulo: "e mais consequências",
    ano: "1495- D.R.",
    duracao: "",
    cidade: "Neverwinter",
    detalhes: "",
  },
];

export default Timeline;
